fix: local full run

diff --git a/yardstick_benchmark/games/minecraft/workload/walkaround_deploy.yml b/yardstick_benchmark/games/minecraft/workload/walkaround_deploy.yml
--- a/yardstick_benchmark/games/minecraft/workload/walkaround_deploy.yml
+++ b/yardstick_benchmark/games/minecraft/workload/walkaround_deploy.yml
@@ -1,31 +1,37 @@
 ---
 - name: Deploy Minecraft WalkAround workload
   gather_facts: true
-  hosts: all
+  hosts: bot
   tasks:
     - debug:
         msg: "working directory is: {{wd}}"
     - file:
         path: "{{ wd }}"
         state: directory
+    
     - name: Check if nvm is available
       shell: |
-        source ~/.bashrc
-        nvm --version
+        source ~/.nvm/nvm.sh && nvm --version
       register: nvm_version
-      failed_when: nvm_version.rc != 0 and nvm_version.rc != 127
+      #failed_when: nvm_version.rc != 0 and nvm_version.rc != 127
+      when: false
+      args:
+        executable: /bin/bash
+    
     - name: Install nvm
       shell: |
-        wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
-      when: nvm_version.rc == 127
+        if ! test -f ~/.nvm/nvm.sh
+        then
+          wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
+        fi
+    
     - name: Install node 18 and Mineflayer
-      shell:
-        cmd: |
-          source ~/.bashrc
-          nvm install 18
-          npm install mineflayer
-          npm install mineflayer-pathfinder
-        chdir: "{{wd}}"
+      shell: |
+        source ~/.nvm/nvm.sh && nvm install 18 && npm install mineflayer && npm install mineflayer-pathfinder
+      args:
+        executable: /bin/bash
+        chdir: "{{ wd }}"
+    
     - name: Checkout RCON client
       git:
         repo: https://github.com/tehbeard/node-rcon.git
